spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8
      username: root
      password: liyanjia
      initial-size: 5
      max-active: 30
      max-wait: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  redis:
    host: localhost
    port: 6379
    database: 1
  elasticsearch:
    rest:
      uris: http://localhost:9200




